### ISSUE TITLE
Game won't start on newest version

### ISSUE THREAD

**Issue by etroozo** [CorgiTaco/Enhanced-Celestials#56] opened 2021-08-18 20:56 UTC
Hey, love this mod, but I haven't been able to start up my game on the latest version (2.0.0, 2.0.1, 2.0.2, 2.0.3 all fail). It starts the forge loading screen for like 5 or so seconds and then kicks me back to the launcher.
I'm running a ton of mods so I'm assuming there's some conflict?

MC version: 1.16.5
Mod version: 2.0.0 - 2.0.3
Forge version: 36.2.0
Modlist: https://pastebin.com/e2MH3eMA (except the newest EC version rather than the old one)
Log: https://pastebin.com/zvTnSADC

Help would be much appreciated. I'm looking forward to tinkering with all of the new settings. Thanks in advance.

**Comment by JojoMeowstic** [comment] 2021-08-20 05:01
Same I'm working on a modpack and It worked fine until I put this mod in it
[Modlist.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/7019221/Modlist.txt)
This is my mod list

**Comment by JojoMeowstic** [comment] 2021-08-20 05:02
I'm playing on the new fabric 1.17.1

**Comment by CorgiTaco** [comment] 2021-08-20 05:18
A mod list is irrelevant here, send a latest.log @JojoMeowstic

**Comment by CorgiTaco** [comment] 2021-08-20 06:10
this is mixin being stupid it seems, i've archived the file for the time being

**Comment by CorgiTaco** [comment] 2021-08-22 02:23
@JojoMeowstic should be fixed on fabric: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials-fabric/files/3433877

**Comment by Devestatio** [comment] 2021-08-24 02:36
Ok, so it seems I wasn't alone with the issue on adding the mod for MC 1.16.5 on forge, looks like you got it worked out on Fabric though, will keep an eye out for a forge update. Not sure what you mean by you archived the file though? I am using version 2.0.5 for forge, should we be using an alternate version for now?

**Comment by Griefed** [comment] 2021-09-01 16:04
I've tried Forge versions 2.0.7 through 2.0.0 and all of them are throwing Mixin errors. The crash report is the same every time: https://haste.zneix.eu/uvozufowew.rb
1.0.4 works fine, so I will stick to that version for the time being. 🙂

**Comment by Griefed** [comment] 2021-09-08 16:06
I can confirm that as of version 2.0.8 Enhanced Celestials and Botania are playing along nicely. Thanks for the fix!
Specifically the versions:
Forge 36.2.4
Botania 419
Enhanced Celestials 2.0.8

**Closed as completed** 2021-09-08 17:09 UTC
